slam_toolbox:
  ros__parameters:
    use_sim_time: true
    map_update_interval: 1.0
    minimum_travel_distance: 0.15
    minimum_travel_heading: 0.15
    min_laser_range: 0.12
    max_laser_range: 5.0
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
